### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by douglaslauren** [guidi/bancointer_dotnet#8]
Estou com um problema e não estou conseguindo identificar o problema, poderia me ajudar?

No método Gerar Boleto está retornando erro "O código de status de resposta não indica êxito: 400 (Bad Request)."

Que significa "Requisição inválida"

**Comment by guidi** [comment]
Erro 401 é problema de autenticação, reveja o clientid e clientsecret e confirma os escopos na aplicação que vc criou na conta PJ do banco inter.

**Comment by douglaslauren** [comment]
> Estou com um problema e não estou conseguindo identificar o problema, poderia me ajudar?
> 
> No Metodo `private static async Task<DefaultTokenDTO> ObterToken(String Escopo)` está dando erro
> 
> Na linha `var respostaRequisicao = await httpClient.PostAsync(URL_TOKEN, conteudo);` tem esse retorno
> 
> {StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers: { X-Ca-Err: 201 X-Rate-Limit-Remaining: 4 X-Rate-Limit-Time: 1673527348987 X-Request-Id: d9d294c9-4f42-408c-bba2-662c56441d35 Date: Thu, 12 Jan 2023 12:41:28 GMT Content-Length: 55 Content-Type: application/json }}



> 

Obrigado, verifiquei e estava errado mesmo.

Agora está funcionando certinho Valeu!
